name = "Matte"
uuid = "b0b859e2-eb2e-45cd-bd98-8fc21bfdc9fa"
authors = ["Angus Moore <18376371+angusmoore@users.noreply.github.com>"]
version = "0.1.0"

[deps]
Genie = "c43c736e-a2d1-11e8-161f-af95117fbd1e"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"

[compat]
julia = "^1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"

[targets]
test = ["Test", "HTTP"]
